build:
	nasm -f elf p5.asm
	ld -m elf_i386 p5.o -o ../../bin/practica5.exe ../../lib/libpc_io.a

	nasm -f elf p5a.asm
	ld -m elf_i386 p5a.o -o ../../bin/practica5a.exe ../../lib/libpc_io.a

	nasm -f elf p5b.asm
	ld -m elf_i386 p5b.o -o ../../bin/practica5b.exe ../../lib/libpc_io.a

	nasm -f elf p5c.asm
	ld -m elf_i386 p5c.o -o ../../bin/practica5c.exe ../../lib/libpc_io.a

	nasm -f elf p5d.asm
	ld -m elf_i386 p5d.o -o ../../bin/practica5d.exe ../../lib/libpc_io.a

	nasm -f elf p5e.asm
	ld -m elf_i386 p5e.o -o ../../bin/practica5e.exe ../../lib/libpc_io.a

	nasm -f elf p5f.asm
	ld -m elf_i386 p5f.o -o ../../bin/practica5f.exe ../../lib/libpc_io.a

run:
	./../../bin/practica5.exe

runa:
	./../../bin/practica5a.exe

runb:
	./../../bin/practica5b.exe

runc:
	./../../bin/practica5c.exe

rund:
	./../../bin/practica5d.exe

rune:
	./../../bin/practica5e.exe

runf:
	./../../bin/practica5f.exe
